const SUPABASE_URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co';
const SUPABASE_KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let map, markers=[];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>`${Number(v).toFixed(4)} / liter`;
function markerIcon(){return L.divIcon({className:'haga-marker',html:'<span class="truck-marker">🚛</span>',iconSize:[42,42],iconAnchor:[21,21]})}
function initMap(){map=L.map('map',{zoomControl:false}).setView([9.563,44.068],12);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO',maxZoom:19}).addTo(map)}
function clearMarkers(){markers.forEach(m=>map.removeLayer(m));markers=[]}
function renderTrucks(rows){const list=document.getElementById('truckCards');document.getElementById('truckCount').textContent=rows.length;clearMarkers();if(!rows.length){list.innerHTML='<div class="empty-state"><div>🚛</div><h3>No water trucks yet</h3><p>Be the first verified truck operator to post your service.</p><button class="btn btn-primary" data-open-post>Post your truck</button></div>';}else{list.innerHTML=rows.map(t=>`<article class="truck-card"><div class="truck-card-top"><div class="truck-avatar">🚛</div><div class="truck-name"><strong>${esc(t.name)}</strong><span>${esc(t.location_label||'Location available')}</span></div><span class="live-badge">AVAILABLE</span></div><div class="truck-details"><div><small>PRICE / LITER</small><strong>${money(t.price_per_liter)}</strong></div><a class="call-btn" href="tel:${esc(t.phone)}">Call</a></div></article>`).join('');list.querySelectorAll('[data-open-post]').forEach(b=>b.addEventListener('click',openPost));rows.forEach(t=>{const m=L.marker([t.latitude,t.longitude],{icon:markerIcon()}).addTo(map).bindPopup(`<div class="popup"><strong>${esc(t.name)}</strong><br><span>${esc(t.location_label||'Water truck')}</span><br><b>${money(t.price_per_liter)}</b><br><a href="tel:${esc(t.phone)}">Call ${esc(t.phone)}</a></div>`);markers.push(m)})}
function getLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location is not supported on this device.'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:12000,maximumAge:0})})}
async function loadTrucks(){const {data,error}=await db.from('water_trucks').select('*').eq('available',true).order('created_at',{ascending:false});if(error){console.error(error);document.getElementById('truckCards').innerHTML='<div class="empty-state"><h3>Could not load trucks</h3><p>Please refresh and try again.</p></div>';return}renderTrucks(data||[])}
function showAuth(mode='login'){document.getElementById('authModal').classList.add('open');document.getElementById('authMode').value=mode;document.getElementById('authTitle').textContent=mode==='login'?'Welcome back':'Create your HAGA account';document.getElementById('authSubmit').textContent=mode==='login'?'Log in':'Create account';document.getElementById('signupFields').style.display=mode==='signup'?'grid':'none';document.getElementById('authSwitch').innerHTML=mode==='login'?`New to HAGA? <button type="button" data-auth-switch="signup">Create an account</button>`:`Already have an account? <button type="button" data-auth-switch="login">Log in</button>`}
function closeModal(id){document.getElementById(id).classList.remove('open')}
document.addEventListener('click',e=>{const sw=e.target.closest('[data-auth-switch]');if(sw)showAuth(sw.dataset.authSwitch);if(e.target.matches('[data-close-auth]'))closeModal('authModal');if(e.target.matches('[data-close-post]'))closeModal('postModal');if(e.target.matches('[data-open-login]'))showAuth('login');if(e.target.matches('[data-open-signup]'))showAuth('signup');if(e.target.matches('[data-open-post]'))openPost();});
async function refreshUser(){const {data:{user}}=await db.auth.getUser();document.querySelectorAll('[data-auth-area]').forEach(el=>el.innerHTML=user?`<button class="account-btn" data-open-post>Post a water truck</button><button class="logout-btn" id="logoutBtn">Log out</button>`:`<button class="login-btn" data-open-login>Log in</button><button class="signup-btn" data-open-signup>Sign up</button>`);const logout=document.getElementById('logoutBtn');if(logout)logout.onclick=async()=>{await db.auth.signOut();refreshUser()};return user}
document.getElementById('authForm').addEventListener('submit',async e=>{e.preventDefault();const mode=document.getElementById('authMode').value;const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;if(mode==='login'){const {error}=await db.auth.signInWithPassword({email,password});if(error)return alert(error.message);closeModal('authModal');await refreshUser();return}const full_name=document.getElementById('authName').value.trim();const phone=document.getElementById('authPhone').value.trim();const role=document.getElementById('authRole').value;const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name,phone,role}}});if(error)return alert(error.message);if(data.session){closeModal('authModal');await refreshUser()}else alert('Account created. Check your email if confirmation is enabled, then log in.');});
function openPost(){db.auth.getUser().then(({data:{user}})=>{if(!user){showAuth('login');return}document.getElementById('postModal').classList.add('open')})}
document.getElementById('locateBtn').addEventListener('click',async()=>{const btn=document.getElementById('locateBtn');btn.textContent='Requesting location…';try{const p=await getLocation();document.getElementById('lat').value=p.coords.latitude;document.getElementById('lng').value=p.coords.longitude;document.getElementById('locationText').textContent=`Location captured: ${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`;btn.textContent='✓ Location added'}catch(err){btn.textContent='Use my location';alert('HAGA needs location access to place your truck on the map. Please allow location access and try again.')}});
document.getElementById('postForm').addEventListener('submit',async e=>{e.preventDefault();const {data:{user}}=await db.auth.getUser();if(!user)return showAuth('login');const lat=Number(document.getElementById('lat').value),lng=Number(document.getElementById('lng').value);if(!lat||!lng)return alert('Tap “Use my location” first so customers can find your truck.');const payload={owner_id:user.id,name:document.getElementById('truckName').value.trim(),phone:document.getElementById('truckPhone').value.trim(),price_per_liter:Number(document.getElementById('priceLiter').value),latitude:lat,longitude:lng,location_label:document.getElementById('locationLabel').value.trim()||'Current location',available:true};const {error}=await db.from('water_trucks').insert(payload);if(error)return alert(error.message);e.target.reset();document.getElementById('lat').value='';document.getElementById('lng').value='';document.getElementById('locationText').textContent='No location selected';document.getElementById('locateBtn').textContent='Use my location';closeModal('postModal');await loadTrucks();alert('Your water truck is now live on HAGA.');});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal('authModal');closeModal('postModal')}});
initMap();loadTrucks();refreshUser();